dist: bionic

os:
  - linux

branches:
  only:
  - master

services:
  - docker

arch:
  - amd64
  - aarch64

addons:
  apt:
    update: true
  hosts:
    - node2

# Build Test
script:
  - cd openEuler20.03
  - if [  "$(uname -m)" == "aarch64" ]; then
      docker build -t kunpengcompute/openeuler:rpmbuild.aarch64 aarch64
    else
      docker build -t kunpengcompute/openeuler:rpmbuild.x86_64 x86_64
    fi

# Deploy to dockerhub
deploy:
  provider: script
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - if [  "$(uname -m)" == "aarch64" ]; then
        docker push kunpengcompute/openeuler:rpmbuild.aarch64
      else
        docker push kunpengcompute/openeuler:rpmbuild.x86_64
      fi
  on:
    branch: master
